//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftSpottingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpottingLog
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Registration { get; set; }
        public string Location { get; set; }
        public System.DateTime SpottedWhen { get; set; }
        public string Image { get; set; }
    }
}
